[env:upezy_wroom]
platform = espressif32
board = upesy_wroom
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps =
    bblanchon/ArduinoJson@^6.21.2
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit Unified Sensor@^1.1.9
    adafruit/DHT sensor library@^1.4.4
    arduinogetstarted/ezButton@^1.0.4
    miguel5612/MQUnifiedsensor@^3.0.0
    milesburton/DallasTemperature@^3.11.0
    arduino-libraries/NTPClient@^3.2.1

[platformio]
description = hydroponics-march
